"""add_scheduled_tasks_models

Revision ID: 544da5d8c331
Revises: f54bb2e98366
Create Date: 2025-07-26 20:57:53.844155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544da5d8c331'
down_revision: Union[str, None] = 'f54bb2e98366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_args', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_spec', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='scheduled', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_task_id'), 'scheduled_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_scheduled_tasks_task_name'), 'scheduled_tasks', ['task_name'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_task_type'), 'scheduled_tasks', ['task_type'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_task_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_task_id'], ['scheduled_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_executions_execution_id'), 'task_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_execution_id'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_scheduled_tasks_task_type'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_task_name'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_task_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
